### ISSUE TITLE
Allow control to be deselected

### ISSUE THREAD

**Issue by simoami** [gmarm/BetterSegmentedControl#10]
Hello,
I have a use-case to allow a new user to select his/her gender. I want the control to be initially deselected to prevent the user from skipping the setup screen with the default "Male" option. SO an empty option would help force the user to select an option. UISegmentedControl allows this:

```
control.selectedSegmentIndex = UISegmentedControlNoSegment
```
perhaps you could allow `index` and `setIndex()` to accept -1 as an exception. This is common standard for indexes.

**Comment by gmarm** [comment]
Hmm... that's interesting! It shouldn't be that big of a change but some logic needs to be changed since I'm using a `UInt` for the index and not an `Int` like `UISegmentedControl` does.

I'm adding this to the TODO list, thanks!

**Comment by simoami** [comment]
thanks for the update. Can't wait to get it!

**Comment by pjebs** [comment]
Has this been implemented?

**Comment by gmarm** [comment]
@pjebs No, not yet. When I implement something I link the Pull Request it was implemented in.

**Comment by simoami** [comment]
@gmarm Any luck?

**Comment by gmarm** [comment]
@simoami unfortunately not. 

I understand the need for this and I see it's a popular request, however I haven't had much time for OSS lately. 

Will do my best to work on it soon.
