### ISSUE TITLE
numberOfLines is not available in latest version

### ISSUE THREAD

**Issue by mkeremkeskin** [gmarm/BetterSegmentedControl#101]
With the latest version, ability to change **numberOfLines** is removed as I see. I was able to use it with version 0.8. 

After I looked to the code I found the way below for setting it. It's not the ideal way I guess but it works for me 😄

```
for element in segmentedControl.segments {
      ((element as! LabelSegment).normalView as! UILabel).numberOfLines = 2
      ((element as! LabelSegment).selectedView as! UILabel).numberOfLines = 2
}
```
Is there any more preferred way for doing this, if so can you please guide me?

Thanks already.

**Comment by gmarm** [comment]
I would add the `numberOfLines` in the `LabelSegment` if you intend fork, or create a new custom segment for your use case.

**Comment by mkeremkeskin** [comment]
New custom segment can be a good idea, thanks for the suggestion.

**Comment by Md-Rais** [comment]
Hi, Thanks for this great tool. 
I am in need of number of lines option in the segmented control. Please let me know if there is any other way to set large text as segment title. Thanks

**Comment by SDPrio** [comment]
I am also missing the MultiLine option from version 0.8. While creating a custom segment could be a solution I think this is a quite common use case and it would be great if it would included in the default LabelSegement

**Comment by gmarm** [comment]
Fixed as part of https://github.com/gmarm/BetterSegmentedControl/pull/112.
