### ISSUE TITLE
Set colour for selected and normal text for when view instantiate

### ISSUE THREAD

**Issue by ansonngch** [gmarm/BetterSegmentedControl#102]

**Comment by DavidCollinsNZ** [comment]
I think I may have had the same issue as you. I used IB for layout of the view, then code for customizing the BetterSegmentedControl view. Is that what you're doing?

Anyway, i put the .options, and .segment into layoutSubviews function of my View

**Comment by gmarm** [comment]
I cannot understand what the issue is about.

Can someone clarify?

**Comment by ansonngch** [comment]
@gmarm what I'm trying to ask is if there is any methods for us to customise the normal text color for different screens?

**Comment by gmarm** [comment]
If you're using different instances of the control, then you can surely configure the controls with different colors.

If you're using the same instance and want different colors per segment you can also do that by creating segments individually (not using the factory method).

**Comment by ansonngch** [comment]
do you have any example codes to show?

**Comment by gmarm** [comment]
Inconsistencies between IB and runtime were fixed as part of https://github.com/gmarm/BetterSegmentedControl/pull/142
