### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "BetterSegmentedControl":

### ISSUE THREAD

**Issue by SubZane** [gmarm/BetterSegmentedControl#108]
``
[!] CocoaPods could not find compatible versions for pod "BetterSegmentedControl":
  In Podfile:
    BetterSegmentedControl (~> 1.1)

None of your spec sources contain a spec satisfying the dependency: `BetterSegmentedControl (~> 1.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
``

If I remove version info, it downloads, but version 1.0.3

**Comment by gmarm** [comment]
Have you tried `pod install --repo-update`?

**Comment by AlexanderZbirnik** [comment]
I have same issue and "pod install --repo-update" don't help me

**Comment by rlester** [comment]
Looks like the 1.1 spec hasn't been uploaded to CocoaPods.

https://github.com/CocoaPods/Specs/tree/c7b609937c9cca9daf29cf05ae213ca98aa9e0ae/Specs/3/2/5/BetterSegmentedControl

**Comment by gmarm** [comment]
Should be fixed now!
