### ISSUE TITLE
Different fonts for titleLabels and selectedTitleLabels

### ISSUE THREAD

**Issue by Chico741** [gmarm/BetterSegmentedControl#11]
First thanks for the great work, I'm just missing the possibility to set different fonts for titleLabels and selectedTitleLabels. This can make sense if you wish to have a regular font in titleLabels and the same bold font of the same size in selectedTitleLabels. In this case the transition looks quite well and the selected item can be better highlighted. What do you think?

**Comment by gmarm** [comment]
This isn't a bad idea, however I am a little skeptic as to how the transition might look.

Considering a public `selectedTitleFont` property is exposed, it could result in some really ugly transitions if no "matching" font is passed to the `titleFont` property. But then again, you could argue that there's a similar issue with the colors. So I guess it's the responsibility of the consumer to use this appropriately.

I'm adding this to the TODOs and will probably work on it soon!

**Comment by gmarm** [comment]
Added with https://github.com/gmarm/BetterSegmentedControl/pull/13
