### ISSUE TITLE
Bump swift version for v1.1

### ISSUE THREAD

**Issue by borut-t** [gmarm/BetterSegmentedControl#110]
Version v1.1 is upgraded to swift 5 but the podspec `s.swift_version` still points to swift 4.2.
Please update to 
```
s.swift_version = '5.0'
```

**Comment by gmarm** [comment]
Oh snap, you wanna open a PR for that?

**Comment by borut-t** [comment]
I'll try.

**Comment by borut-t** [comment]
@gmarm [done](https://github.com/gmarm/BetterSegmentedControl/pull/111)

**Comment by gmarm** [comment]
Thanks @borut-t ! Fixed as part of https://github.com/gmarm/BetterSegmentedControl/pull/111.

**Comment by borut-t** [comment]
@gmarm can you please push the update to cocopods trunk as well?
