### ISSUE TITLE
Question: Drop shadow to the IndicatorView 

### ISSUE THREAD

**Issue by akeem554** [gmarm/BetterSegmentedControl#118]
Sorry for this question, but am i able to add a drop shadow to the indicator view? I believe it should be possible since the indicatorView is an open subclass of UIView. Ive tried using CALayer properties but to no avail. if it is possible, can anyone give me any guidance? thank you

**Comment by gmarm** [comment]
hey @akeem554 , there was a bug that was fixed with https://github.com/gmarm/BetterSegmentedControl/pull/121.

It's possible to achieve that now. You can check the `appleStyled` class method on the control for an example.
