### ISSUE TITLE
iOS 7

### ISSUE THREAD

**Issue by pjebs** [gmarm/BetterSegmentedControl#12]
Will this work with iOS 7?
I don't have an iOS 7 device but I need to target iOS 7 min.
Are you using any code that is iOS 8+

**Comment by pjebs** [comment]
If the code is based on NYSegmentedControl, then it probably will work with iOS 7

**Comment by gmarm** [comment]
The code is not based on NYSegmentedControl.

I don't believe there's API usage that isn't there on iOS 7. However, considering there is no way to build against it, I would strongly discourage you from using it if you need to target iOS 7.
