### ISSUE TITLE
Apply Shadow to selected segment

### ISSUE THREAD

**Issue by najeeburrehman-brainx** [gmarm/BetterSegmentedControl#132]
Is there any option to give shadow around the selected segment like this one: 
<img width="238" alt="Screenshot 2020-05-08 at 3 52 59 PM" src="https://user-images.githubusercontent.com/37113343/81399209-11c2bc80-9144-11ea-838f-188cf801e345.png">

**Comment by gmarm** [comment]
Yes the `indicatorView` is `public`. You should be able to add a shadow to it like any other view.

**Comment by najeeburrehman-brainx** [comment]
But its not working...

**Comment by gmarm** [comment]
There’s an example here: https://github.com/gmarm/BetterSegmentedControl/blob/3fa5b92b3ac4b8a0134db5eb6fb40b6023b4aaaf/Pod/Classes/BetterSegmentedControl.swift#L380

Let me know if this helps

**Comment by najeeburrehman-brainx** [comment]
It will add shadow to both the segments I guess. But can we add it the single segment: the selected one.
Thanks.

**Comment by najeeburrehman-brainx** [comment]
@gmarm is there any option for this ?
