### ISSUE TITLE
error: 'BetterSegmentedControl' is not a member type of 'BetterSegmentedControl'

### ISSUE THREAD

**Issue by firetrap** [gmarm/BetterSegmentedControl#133]
I don't know what more to try, tried cleaning project, derived data, install by carthage, install by SPM and always the same error:
error: 'BetterSegmentedControl' is not a member type of 'BetterSegmentedControl'

I'm only adding a View to Xib adding BetterSegmentedControl as CustomView and creating an IBOutlet.

CocoaPods it's not an option

Can somebody help?

PS: Version 1.3

**Comment by gmarm** [comment]
Have you taken a look at the example app? There are XIB examples there that might help you.

If not, please share more info / screenshots of your problem to further help you out.

In the worst case I would imagine that this could be a problem with integration via SPM / Carthage, although unlikely.

**Comment by gmarm** [comment]
In IB, after setting the Class at the top, make sure to also set the Module manually. That should fix your issue,

![Screenshot 2020-10-21 at 13 20 18](https://user-images.githubusercontent.com/1718656/96712963-30d6a300-13a0-11eb-93b9-4fc75e45043b.png)
