### ISSUE TITLE
Indicator size

### ISSUE THREAD

**Issue by BaileyM** [gmarm/BetterSegmentedControl#134]
I am trying to change the size of the selected segment indicator. I tried indicatorView.transform = CGAffineTransform(scaleX: 2, y: 2) but it does not change the indicator's appearance. I want to make it a little bigger than the unselected segments.

**Comment by itinsync** [comment]
@BaileyM Did you achieve it?

**Comment by BaileyM** [comment]
No, but our designers were satisfied with the default appearance, so this is no longer an issue for me.
