### ISSUE TITLE
LabelSegment.segments normalTextColor and selectedTextColor not working

### ISSUE THREAD

**Issue by firetrap** [gmarm/BetterSegmentedControl#135]
**Using version 1.3**

  @IBOutlet weak var betterSegmentedControl: BetterSegmentedControl! {

        didSet {
            betterSegmentedControl.cornerRadius = 20
            betterSegmentedControl.backgroundColor = UIColor.clear
            betterSegmentedControl.indicatorViewBackgroundColor = UIColor.red
            
            let titles: [String] = ["111111", "22222222"]

            betterSegmentedControl.segments = LabelSegment.segments(
                withTitles: titles, normalFont: UIFont.systemFont(ofSize: 12), normalTextColor: UIColor.white ,selectedFont: UIFont.systemFont(ofSize: 12), selectedTextColor: UIColor.white)
        }
    }

PS: The font is applied correctly so the problem it's only the color.

![Screenshot 2020-06-26 at 14 54 19](https://user-images.githubusercontent.com/655828/85864868-faf02c00-b7bc-11ea-813f-df82433f6638.png)

**Comment by digabriel** [comment]
The same is happening to me, only when using from Interface Builder. When I create the control on code, using the default initializer, everything works well.

**Comment by gmarm** [comment]
The inconsistencies between IB and runtime have been as part of https://github.com/gmarm/BetterSegmentedControl/pull/142
