### ISSUE TITLE
Pod update failed. Could not find remote branch 2.0 to clone.

### ISSUE THREAD

**Issue by OriTheElf** [gmarm/BetterSegmentedControl#143]
[!] Error installing BetterSegmentedControl
[!] /usr/bin/git clone https://github.com/gmarm/BetterSegmentedControl.git /var/folders/50/sn2p3h_s0jg9x0xmfl6w_m140000gn/T/d20201021-50370-2cdc6q --template= --single-branch --depth 1 --branch 2.0

Cloning into '/var/folders/50/sn2p3h_s0jg9x0xmfl6w_m140000gn/T/d20201021-50370-2cdc6q'...
warning: Could not find remote branch 2.0 to clone.
fatal: Remote branch 2.0 not found in upstream origin

**Comment by gmarm** [comment]
Fixed in https://github.com/gmarm/BetterSegmentedControl/pull/146
