### ISSUE TITLE
Feature Request: outline main part of control outline (easy?)

### ISSUE THREAD

**Issue by AccuPhoenix01** [gmarm/BetterSegmentedControl#147]
Could you add outlining to the main part of the control? This would allow a design like such, as my design dept has asked me to create:

![image](https://user-images.githubusercontent.com/46455562/100143638-a16f5480-2e63-11eb-8b09-ddcaa5505048.png)

```
@IBInspectable public var outlineColor: UIColor? {
        get {
            UIColor(cgColor: layer.borderColor ?? UIColor.clear.cgColor)
        }
        set {
            layer.borderColor = newValue?.cgColor
        }
    }
    
    @IBInspectable public var borderWidth: CGFloat {
        get {
            layer.borderWidth
        }
        set {
            layer.borderWidth = newValue
        }
    }
```

Thanks, Chris

**Comment by gmarm** [comment]
I intentionally didn't add this as this can be achieved easily via `layer.borderColor`, `layer.borderWidth` like in any `UIView` as shown above. Adding them would only duplicate functionality.
