### ISSUE TITLE
Objective C

### ISSUE THREAD

**Issue by mommyme** [gmarm/BetterSegmentedControl#15]
For those of us that don't yet know Swift, you don't happen to have an Objective C copy of this control, do you? Thanks, it is a great control.

**Comment by gmarm** [comment]
Nope, no Objective-C edition, sorry!

**Comment by mommyme** [comment]
I was just coming in to close this. I easily integrated the Swift version. Thank you!

**Comment by SanaAhmed** [comment]
@inPhilly can you please share how you did it? am unable to declare BetterSegmentedControl in objective C
