### ISSUE TITLE
Carthage error! It has no shared framework schemes

### ISSUE THREAD

**Issue by calvingit** [gmarm/BetterSegmentedControl#29]
![qq20160923-0](https://cloud.githubusercontent.com/assets/2109371/18772474/e40ba514-8179-11e6-9e9e-0ddc8b9aaf15.png)

**Comment by gmarm** [comment]
Hey, has this been fixed by https://github.com/gmarm/BetterSegmentedControl/pull/30?

**Comment by calvingit** [comment]
Yes, I'll close this issue.
