### ISSUE TITLE
Similar to DGRunkeeperSwitch

### ISSUE THREAD

**Issue by efremidze** [gmarm/BetterSegmentedControl#3]
My version also handles multiple options.
https://github.com/efremidze/DGRunkeeperSwitch

**Comment by gmarm** [comment]
Hey @efremidze , thanks for opening the repo's first issue! 

I certainly did look into many different repos while writing BetterSegmentedControl, the original DGRunkeeperSwitch included of course. However I didn't get a chance to look into yours which does share a similar logic for adding multiple labels. What do you expect from opening this issue?

I see that you use `forEach()` for iterating over the labels and it seems better than `map()` which I'm using. Would you like to submit a PR from that?

**Comment by efremidze** [comment]
I was hoping to merge our changes and make one amazing segmented control. :smile:

**Comment by gmarm** [comment]
Yeah, feel free to do that. 

Closing the issue and see you in a PR then!
