### ISSUE TITLE
Views not correct when switching between options (titles)

### ISSUE THREAD

**Issue by luuk-harmeling** [gmarm/BetterSegmentedControl#31]
I found some strange behaviour while using BetterSegmentedControl on Swift 3 / Xcode 8. 
I'm using the control to switch in between "all locations" and "favourite locations" in my App. I initialize the controls once using the constructor. 

Then further on , I made a code that changes a number in the titles of the segmentedcontrol. (e.g. from 4 to 5 favourite locations when you favourite one). Below here a snippet of code that shows how i do the actual changing of titles.

<img width="838" alt="screen shot 2016-09-27 at 15 17 58" src="https://cloud.githubusercontent.com/assets/11074131/18875317/985d93c6-84c5-11e6-847f-277bf857c93c.png">

Here's where the strange behaviour occurs, the selected text and not-selected texts of that title both show (see below).

<img width="374" alt="screen shot 2016-09-27 at 15 10 59" src="https://cloud.githubusercontent.com/assets/11074131/18875269/58f3f7de-84c5-11e6-9bb0-04172f009dee.png">

As you can see the "All locations (5)" labels for active and non active are both represented. 

This worked perfectly on Swift 2.2. 

Any idea's for this issue?

Kind regards,

Luuk

**Comment by gmarm** [comment]
Hmm... I can think of a couple of things.

It seems that you are using different `titleFont` and `selectedTitleFont`, which is totally fine, but that's what is causing the issue to be so visible. Maybe your `indicatorViewBackgroundColor` is set to `.clear`. If so, set a different color.

Let me know if this helps.

**Comment by luuk-harmeling** [comment]
Hi gmarm,

First of all: Thank you for your quick response! 

Your insight totally solved my issue, I clearly made a mistake here and its fixed now! I greatly appreciate your help. I'll close this issue.


Kind regards,

Luuk
