### ISSUE TITLE
wish icon type segment and icon+text type

### ISSUE THREAD

**Issue by longxianlin** [gmarm/BetterSegmentedControl#32]

**Comment by gmarm** [comment]
Sorry for the late response.

This is something that is currently not supported. I am working on this on a separate branch however there is no release frame at the moment.

**Comment by HappyIosDeveloper** [comment]
I won't do this myself but maybe with a little creativity you could do it:

        let icon = UIImageView()
        icon.image = #imageLiteral(resourceName: "TOSES")
        icon.frame.size = CGSize(width: 30, height: 30)
        migrationSegmentController.segments[0].normalView.addSubview(icon)
        migrationSegmentController.segments[0].selectedView.addSubview(icon)
