### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by dleonard00** [gmarm/BetterSegmentedControl#36]
When building for carthage I am seeing the following error:
```
*** Skipped building BetterSegmentedControl due to the error:
Dependency "BetterSegmentedControl" has no shared framework schemes for any of the platforms: iOS
```

The command I am running: `carthage update --platform iOS`

A workaround I have found that seems to work for now: Change `github "gmarm/BetterSegmentedControl" ~> 0.5` as indicated in the readme to `github "gmarm/BetterSegmentedControl" "master"`

**Comment by gmarm** [comment]
Yes, this has been fixed in https://github.com/gmarm/BetterSegmentedControl/pull/33 but I have not created a new release since.

I will be creating the new release and then you will be able to use `~> 0.5` instead of `master`.
