### ISSUE TITLE
Change views with BetterSegmentedControl?

### ISSUE THREAD

**Issue by amikhaielHacker** [gmarm/BetterSegmentedControl#40]
How to do?

**Comment by gmarm** [comment]
Could you be a little more specific?

**Comment by amikhaielHacker** [comment]
I would like to switch between UIViewController...

**Comment by KaushalElsewhere** [comment]
@amikhaielHacker use UIPageViewController for switching between ViewControllers.
then use BetterSegmentedControl(or simple UISegmentedControl) to show selected index (of the view Controller).
