### ISSUE TITLE
CornerRadius issue.

### ISSUE THREAD

**Issue by moiseevanton** [gmarm/BetterSegmentedControl#41]
Hey there, I have an issue with the cornerRadius property. For some reason I can't set it to any CGFloat, the compiler gives me an error. I just wanted to make the control round.

Thanks!

**Comment by gmarm** [comment]
Sorry for my late response.

The `cornerRadius` property seems to be working fine on my end. Please have a look at the example project. Both the ViewController and Storyboard contain examples of setting the `cornerRadius`. Closing this for now.
