### ISSUE TITLE
Sigle title issue

### ISSUE THREAD

**Issue by Tatva103** [gmarm/BetterSegmentedControl#42]
Hello,

I want to use this segment control and its work perfectly in more then 1 title but as I have requirement of dynamic segment and problem comes when only 1 title comes.

**Comment by gmarm** [comment]
Sorry for the late response. 

This is something that is not currently supported. What I would suggest is "faking" the effect by adding a UIView with the same look and size of the control on top of it and hide/show the appropriate view based on your single/multiple options logic.
