### ISSUE TITLE
Titles can get cut off, make font size adjust automatically.

### ISSUE THREAD

**Issue by dannymout** [gmarm/BetterSegmentedControl#45]
I'm having an issue, on some devices, the titles can get cut off, and the rest is replaced with three dots. If width is limited, can the font size automatically become smaller to compensate? UILabels already are able to do this, there is an option in Storyboards.

**Comment by dannymout** [comment]
I've tested  `titleLabel.adjustsFontSizeToFitWidth = true` and it does indeed work, but it causes all the labels to have different font sizes. Anyway you could take the title with the largest amount of characters, grab it's font size, and use it for the other titles?

**Comment by gmarm** [comment]
Hey @dannymout thanks for pointing this issue out!

A quick solution would be to add a property that sets the `adjustsFontSizeToFitWidth` property of the title labels, however your last proposal makes more sense I think. I don't think it works best by using the character count, some characters take more space than others. 

I'll definitely look into this soon!

**Comment by dannymout** [comment]
@gmarm Do you know what a solution might be, I might be able to fix it.

**Comment by gmarm** [comment]
Hey @dannymout sorry for the delay.

What is needed here is a way to find the minimum font size amongst all titles and then set it to all the titles so there is a consistent look. I haven't looked into the best way to achieve the first goal. You can have a look into it if you want.

However, this PR: https://github.com/gmarm/BetterSegmentedControl/pull/47, merged recently, might work around the issue. (release still pending for this one)

This doesn't mean of course that wouldn't be a very useful addition.
