### ISSUE TITLE
Carthage Compatible.

### ISSUE THREAD

**Issue by Dershowitz011** [gmarm/BetterSegmentedControl#5]
https://github.com/Dershowitz011/betterSegmentedControl. Are you okay with this?

**Comment by gmarm** [comment]
Is there a particular reason for Carthage support in a separate repo?

**Comment by Dershowitz011** [comment]
Just thought I'd save you the trouble of making it a library. It's perfectly fine in case you've any slightest of the problem @gmarm .

**Comment by gmarm** [comment]
I think it's more convenient for everyone if it's in the same repo is all. I thought there could be some conflict with CocoaPods but that's not the case from what I read. I can probably work on it during the weekend.

**Comment by Dershowitz011** [comment]
Add a link in your README.md, perhaps? That's fine if you want to do it yourself. Let me know though. 

P.S. I like making libraries carthage compatible, that;s all. :D

**Comment by TofPlay** [comment]
@gmarm Take a look at these articles you will understand why it's interesting to support Carthage 😋 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods] (http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

**Comment by gmarm** [comment]
Carthage support added in https://github.com/gmarm/BetterSegmentedControl/pull/8.

Cheers!
