### ISSUE TITLE
set cornerRadius error

### ISSUE THREAD

**Issue by DaokunBai** [gmarm/BetterSegmentedControl#51]
ambiguous use of 'cornerRadius'

**Comment by gmarm** [comment]
Could you please provide some additional details?

**Comment by DaokunBai** [comment]
[error](http://r.photo.store.qq.com/psb?/V11RifNI3gF37U/MBUloQf9RMO.FLo.EoNnaC7YxhqKaTVZtcGJ.X0uqV8!/r/dGoBAAAAAAAA)

**Comment by DaokunBai** [comment]
<img width="1245" alt="wx20170509-172941 2x" src="https://cloud.githubusercontent.com/assets/13998995/25845735/8cc62ec0-34e1-11e7-9c21-d4e6c1157265.png">

**Comment by DaokunBai** [comment]
When modify "cornerRadius" to "viewCornerRadius"

**Comment by DaokunBai** [comment]
When modify "cornerRadius" to "viewCornerRadius" 
The error dismiss
<img width="660" alt="wx20170509-180540 2x" src="https://cloud.githubusercontent.com/assets/13998995/25845900/54cd2810-34e2-11e7-8e6e-2d6e4b31c79d.png">
<img width="1114" alt="wx20170509-180516 2x" src="https://cloud.githubusercontent.com/assets/13998995/25845905/5b697a48-34e2-11e7-8e4d-063c33d3b577.png">

**Comment by gmarm** [comment]
Hmmm... interesting.

The message seems to indicate you might have declared `cornerRadius` before somewhere in your code. One think I can guess is that you have maybe created a `UIView` extension with a `cornerRadius` property, and it conflicts with the property declared in the control itself.

**Comment by DaokunBai** [comment]
YES,Thank you.
I found the declared property in [SwifterSwift](https://github.com/SwifterSwift/SwifterSwift) library.

**Comment by gmarm** [comment]
Happy to help. :)

**Comment by VictorCamargo** [comment]
@DaokunBai and how did you resolved that?
