### ISSUE TITLE
indicator view hiding text

### ISSUE THREAD

**Issue by mateo666** [gmarm/BetterSegmentedControl#56]
Hi, first of all good work !

i need the indicator view to be an image view so i added an image view as a subview of indicator view.
I also need the indicator view to hide the text.

played with it a bit and realized by switching these lines in finishInit it works.

```
    fileprivate func finishInit() {
        layer.masksToBounds = true
        
        addSubview(titleLabelsView)
        **addSubview(selectedTitleLabelsView)
        addSubview(indicatorView)**

```

maybe it would be a good init parameter ?

**Comment by gmarm** [comment]
Hi and thanks! :)

I understand your need however I don't think this is something a lot of people are gonna need!
