### ISSUE TITLE
Hello, betterSegmentedControl can be underline ? I need this style.

### ISSUE THREAD

**Issue by linkfei** [gmarm/BetterSegmentedControl#57]
such as ..

![line](https://user-images.githubusercontent.com/12987627/27117867-31bcd790-510b-11e7-895d-3f721bf82150.png)
![23](https://user-images.githubusercontent.com/12987627/27117897-4b1c6200-510b-11e7-821c-93628ca8c546.png)

**Comment by gmarm** [comment]
You can achieve this by using the `addSubviewToIndicator(_ view: UIView)` method and adding a `UIView` or `UIImage`.
