### ISSUE TITLE
UIImage for each item?

### ISSUE THREAD

**Issue by aloveric** [gmarm/BetterSegmentedControl#58]
Could we use image for each one?

**Comment by yuratrotskyi** [comment]
hmmmm, and no answer...

**Comment by gmarm** [comment]
I have been working on a solution that allows the consumer to create any kind of segments. An image-only segment is present there already.

I intend to merge it back to master as soon as I get image + text segments working.

https://github.com/gmarm/BetterSegmentedControl/tree/SegmentProtocol

Apologies for my very late answer!

**Comment by yuratrotskyi** [comment]
Ok) Thanks you for answer)

пн, 2 квіт. 2018 о 12:15 George Marmaridis <notifications@github.com> пише:

**Comment by morganmattr** [comment]
@gmarm image+text together would rule for segments. Just curious, how can we set just an image-only currently, since you mentioned in this thread that an image-only segment is present?

**Comment by yuratrotskyi** [comment]
I just asked if it possible to set image

вт, 19 черв. 2018 о 00:02 morganmattr <notifications@github.com> пише:
