### ISSUE TITLE
Cannot assign to property: 'selectedTitleColor' setter is inaccessible

### ISSUE THREAD

**Issue by hhelmric** [gmarm/BetterSegmentedControl#62]
When I first create the Segmented Control programmatically, I can set this property via the Options:
`self.modeSelector = BetterSegmentedControl(
            frame: CGRect(x: self.view.bounds.midX - view.bounds.width/8, y: 25, width: view.bounds.width / 4, height: 30.0),
            titles: ["?","18+"],
            index: 0,
            options: [.backgroundColor(Constants.ColorScheme.Seafoam),
                      .titleColor(.white),
                      .indicatorViewBackgroundColor(.white),
                      .selectedTitleColor(Constants.ColorScheme.Seafoam),
                      .cornerRadius(self.modeSelector.frame.height/2),
                      .titleFont(UIFont(name: "HelveticaNeue", size: 16.0)!),
                      .selectedTitleFont(UIFont(name: "HelveticaNeue", size: 16.0)!),
                      .bouncesOnChange(false),
                      .panningDisabled(true)])`

I'm trying to programmatically set the selectedTitleColor but Xcode is telling me this property is inaccessible:
`self.modeSelector.selectedTitleColor = Constants.ColorScheme.Coral`

This part of my code was working fine before I updated to Xcode 9 and Swift 4 but now it's failing the build. Has anyone else had this issue? I can't figure out how to get around it other than commenting it out.

**Comment by gmarm** [comment]
Yes, indeed.

Configuration is now possible via the `options` property. I maybe need to add the change the to the README.

You can replace your old line with the following:
`self.modeSelector.options = [.selectedTitleColor(Constants.ColorScheme.Coral)]`

Let me know if that worked for you.

**Comment by hhelmric** [comment]
That did it, thanks!!

**Comment by vadimleonov** [comment]
@gmarm Unfortunately not working for me because
`Type 'BetterSegmentedControlOption' has no member 'selectedTitleColor'`
