### ISSUE TITLE
setIndex memory leak!

### ISSUE THREAD

**Issue by jackloverde** [gmarm/BetterSegmentedControl#63]
When use setIndex, memory increase from 0 to 120% in 0 secs! And then crash!
And why we have to use do, try to set this ?
Can this be fixed ?
Thanks

**Comment by gmarm** [comment]
I doubt there's a memory leak related to setting the index. Could it be the action you have set after setting the index that causes your issue?

Error handling exists in case the control's consumer attempts setting an index that does not exist in the control.

Could you please share your stacktrace?

**Comment by jackloverde** [comment]
Hi, i remove your try catch for index bound, creating another method that don't do that. Cause i need to set a index for this particular value.
This solution is for my app, i do not recommend to do that.
Thanks for your response :)
