### ISSUE TITLE
Stopped working with Objective-C

### ISSUE THREAD

**Issue by heyarny** [gmarm/BetterSegmentedControl#65]
Seems like you did some changes as now the init method is no longer visible to Obj-C compiler.

**Comment by amorde** [comment]
This is because the enum `BetterSegmentedControlOption` is not representable in Objective-C. There is no easy fix for this, other an undoing the changes made in 5180afa

**Comment by gmarm** [comment]
Oops! You’re absolutely right @heyarny, and true, the breaking changes are in the commit @amorde linked to. 

I absolutely forgot about Objective-C support, my bad. 

I think it makes sense to bring back an initializer for poor Objective-C users. I’ll add it soon. Until that, you can keep using version `0.8`. 

Keeping this issue open until the changes are done.

**Comment by gmarm** [comment]
Moving forward, Objective-C will stop being supported, thus if you still want to use it, you can use version `0.8` as mentioned above.
