### ISSUE TITLE
ERROR: Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by ServusJon** [gmarm/BetterSegmentedControl#67]
Any ideas?

<img width="743" alt="bildschirmfoto 2017-10-24 um 20 21 59" src="https://user-images.githubusercontent.com/783416/31960825-3f8f53f6-b8f9-11e7-9fc1-1ac6b542800d.png">

**Comment by ServusJon** [comment]
Worked before, but after updating the pods I got this error

**Comment by gmarm** [comment]
Hmm, that shouldn't be needed but can you try using `BetterSegmentedControlOption.indicatorViewInset(4.0)`?

**Comment by ServusJon** [comment]
That doesn’t help either :-(

**Comment by gmarm** [comment]
Maybe also `CGFloat(4.0)`?

**Comment by ServusJon** [comment]
I also removed the "options" block entirely and get the same error

**Comment by ServusJon** [comment]
<img width="758" alt="bildschirmfoto 2017-10-24 um 20 35 23" src="https://user-images.githubusercontent.com/783416/31961405-e7ac868e-b8fa-11e7-9f5f-3cc02c1f3932.png">

**Comment by gmarm** [comment]
Have you added `import BetterSegmentedControl` at the top of your file? Also, what is the type of `movementSegmentedControl`?

**Comment by ServusJon** [comment]
I imported it.
I created it like this: var movementSegmentedControl = BetterSegmentedControl()

I didn’t use storyboards

**Comment by ServusJon** [comment]
Any idea?

**Comment by ServusJon** [comment]
@gmarm thoughts on that?

**Comment by gmarm** [comment]
@ServusJon could you reproduce the issue in a demo project that you can share? I have tried replicating the issue but couldn't, thus I couldn't help. :/

**Comment by ServusJon** [comment]
Had to rearrange it. This way it worked:

        movementSegmentedControl = BetterSegmentedControl(frame: CGRect(x: 10.0, y: 100.0, width: view.bounds.width - 20, height: 44.0),
          
          titles: ["Scrolling", "Static"], index: 1, options:              [.indicatorViewInset(CGFloat(4.0)),
            .cornerRadius(CGFloat(22.0)),
            .backgroundColor(.clear),
            .titleColor(UIColor(hexString: "#C1C1C1")!),
            .indicatorViewBackgroundColor(UIColor(hexString: "#E6E6E6")!),
            .selectedTitleColor(UIColor(hexString: "#333333")!),
        ])

**Comment by gmarm** [comment]
Cool, closing this then!
