### ISSUE TITLE
Auto-size mode?

### ISSUE THREAD

**Issue by AlexanderZubkov** [gmarm/BetterSegmentedControl#68]
Do you have any plans on adding proportional to content auto-size mode?

**Comment by AlexanderZubkov** [comment]
fileprivate func elementFrame(forIndex index: UInt) -> CGRect {
      let totalWidth = width - totalInsetSize
      
      let label = titleLabels[Int(index)]
      let textWidth = label.text!.size(withAttributes: [NSAttributedStringKey.font: label.font]).width
      
      var totalTextWidth: CGFloat = 0
      for tempLabel in titleLabels {
        totalTextWidth += tempLabel.text!.size(withAttributes: [NSAttributedStringKey.font: tempLabel.font]).width
      }
      
      var preWidth: CGFloat = 0
      for ind in 0..<Int(index) {
        let tempLabel = titleLabels[ind]
        let tempWidth = tempLabel.text!.size(withAttributes: [NSAttributedStringKey.font: tempLabel.font]).width
        preWidth += (tempWidth * totalWidth) / totalTextWidth
      }
      
      let elementWidth = (textWidth * totalWidth) / totalTextWidth
      
      return CGRect(x: preWidth + indicatorViewInset,
                    y: indicatorViewInset,
                    width: elementWidth,
                    height: height - totalInsetSize)
    }

This may be a bit dirty but hope you get the idea.

![2017-11-24 23 26 41](https://user-images.githubusercontent.com/2487835/33224139-fa442a9a-d16e-11e7-870e-70181c506c86.png)

**Comment by gmarm** [comment]
Added as part of https://github.com/gmarm/BetterSegmentedControl/pull/142

**Comment by Supaplex77** [comment]
Are there any examples of auto-size? How can we use auto-size?
