### ISSUE TITLE
Customize Segmented Control

### ISSUE THREAD

**Issue by ErAshu** [gmarm/BetterSegmentedControl#69]
I have to make fuel level like attached image. Can i achieve with this BetterSegmentedControl?
![screen shot 2018-01-08 at 10 29 26 pm](https://user-images.githubusercontent.com/4178384/34682782-f6a5a79a-f4c5-11e7-9277-4eeffd2a2853.png)

**Comment by gmarm** [comment]
I don't think `BetterSegmentedControl` is the way to go to achieve this. What you should probably look for is a slider component.
