### ISSUE TITLE
Support for segment images?

### ISSUE THREAD

**Issue by jallen** [gmarm/BetterSegmentedControl#7]
Are you interested in supporting segment images?

I was able to create a [mock up](https://github.com/jallen/BetterSegmentedControl) of how it might work using NSTextAttachment and UILabel's attributedText so there are no UIImageViews involved. 

But if you wanted to go in this direction, it would take some work make it backward compatible with the other public properties.

**Comment by gmarm** [comment]
As I mention in the Todos, I'd like to make the control very flexible and allow for any kind of `UIView` subclass to be used as segment. 

The way I have it in my mind is to have the segment view conform to a protocol that requires it to provide a selected and normal mode, much like how it is now with the `UILabel`s. I don't know if I'm missing something right now, but that's the direction I'd like to see this go.

Of course, such a change would necessarily break the current public API.

**Comment by jallen** [comment]
That makes sense and would be a great addition.
