### ISSUE TITLE
how to set budge?

### ISSUE THREAD

**Issue by polaris0227** [gmarm/BetterSegmentedControl#70]
Hi
I want to add budge on this segmented control such as new message count.
Is there any way to do this?
Thanks.

**Comment by gmarm** [comment]
Adding a badge is not supported. The only thing I can think of is adding the message count as part of the title (something like "Messages (2)" for example).

Alternatively, I suggest you create your own fork and add the custom behavior, or add the badges as a completely separate view that is independent of the control, although that might prove a bit tedious.

**Comment by polaris0227** [comment]
Thanks for your quick reply.

I resolved it myself.
Thanks anyway.

On Tue, Jan 16, 2018 at 1:02 PM, George Marmaridis <notifications@github.com
