### ISSUE TITLE
Selected colors for different items.

### ISSUE THREAD

**Issue by ihorodnikoff** [gmarm/BetterSegmentedControl#74]
Is it possible to choose different selected colors for different items?

**Comment by Idomo** [comment]
@gmarm It would be great if you were enable that option, 'Cause right now I was had to do that in the library class (which is very very bad thing to do, but the only way I could do that simple thing): `@IBInspectable /*fileprivate(set)*/ public var indicatorViewBackgroundColor: UIColor?`
Please remove this `fileprivate(set)` or provide some `set` function.
I can't think about reason to not provide access for setters from the code, but allow it from the `IBDesignable`.

Thanks,
Ido.

**Comment by gmarm** [comment]
@ihorodnikoff that is not currently possible

@Idomo I think you are asking about something different. This background color of the indicator view can be set by setting the `indicatorViewBackgroundColor` via the `options` property.

**Comment by Idomo** [comment]
@gmarm I deleted my comment and opened #75, please check it out.
