### ISSUE TITLE
Order of options matters

### ISSUE THREAD

**Issue by pcardoso** [gmarm/BetterSegmentedControl#83]
Took me a while to diagnose, but the order of the options in the constructor matters. I  am using a .indicatorViewInset(0) to implement this design:

![screen shot 2018-09-18 at 12 03 29](https://user-images.githubusercontent.com/516073/45683294-07047f80-bb3b-11e8-94de-451362a5523e.png)

If the indicatorViewInset comes after the cornerRadius option, the cornerRadius setter will update the indicatorView.cornerRadius using the default indicatorViewInset.

```indicatorView.cornerRadius = newValue - indicatorViewInset```

**Comment by gmarm** [comment]
Hmm that shouldn't be the case.

Will look into it.

**Comment by gmarm** [comment]
This should now be fixed as part of https://github.com/gmarm/BetterSegmentedControl/pull/121.
