### ISSUE TITLE
Cannot Accept `UISegmentedControl.noSegment`

### ISSUE THREAD

**Issue by shotat** [gmarm/BetterSegmentedControl#88]
The orignai `SegmentedControl` can accept `.noSegment`, which represents no selection state.
Indices in this library allows `UInt` type but `.noSegment` is a type of `Int` (actually `-1`).

**Comment by DavidCollinsNZ** [comment]
Hi @shotat DId you find a solution to your question?

**Comment by gmarm** [comment]
Support for this has been added as part of https://github.com/gmarm/BetterSegmentedControl/pull/142
