### ISSUE TITLE
how to change border color of segmented control

### ISSUE THREAD

**Issue by zoufishanmehdi** [gmarm/BetterSegmentedControl#89]
Hi, is it possible to change the border color of segmented control? I don't see a property for that. Thank you!

**Comment by gmarm** [comment]
You can use `UIKit`’s `layer.borderColor` property for that I guess.

**Comment by krstns** [comment]
I was just looking for this info... I think it would be awesome to have this exposed by the BetterSegmentedControl so we could see the change in the interface builder. Just a suggestion.

**Comment by gmarm** [comment]
Yep, not a bad idea!
