### ISSUE TITLE
.enabled

### ISSUE THREAD

**Issue by Bizzi-Body** [gmarm/BetterSegmentedControl#9]
Any chance you might implement a enabled/disabled capability?

Something like...

```
    @IBInspectable public var enabled: Bool {
    ........
    }
```

Ideally there would also be a partner "disabled" colour property so that we can specify the dimmed background (could impact the backgroundColor and indicatorViewBackgroundColor properties.

**Comment by gmarm** [comment]
That's not a bad idea. I will look into that!

Your suggestion also got me thinking of implementing disabled segments as well, I'll add this to my list too!
