### ISSUE TITLE
Type 'BetterSegmentedControlOption' has no member 'titleColor'

### ISSUE THREAD

**Issue by jungalwala** [gmarm/BetterSegmentedControl#96]
I am trying to upgrade my project from Swift 3 to Swift 4.2.  I was running BetterSegmentedControl 0.9 but updated to 1.0.3.  Now I am getting the error: 

> Type 'BetterSegmentedControlOption' has no member 'titleColor'

Below is my code:

```
let control = BetterSegmentedControl(
    frame: CGRect(x: 80, y: 0, width: 600, height: 28),
    segments: ["All Tasks".localiz() as! BetterSegmentedControlSegment, 
                        "Incompleted Tasks".localiz() as! BetterSegmentedControlSegment, 
                         "Corrective Actions".localiz() as! BetterSegmentedControlSegment,
                         "Due Today".localiz() as! BetterSegmentedControlSegment],
                index: 0,
                options: [.backgroundColor(UIColorFromRGB(0x8CA1B8)),
                          .titleColor(.black),
                          .indicatorViewBackgroundColor(UIColorFromRGB(0x0077ff)),
                          .selectedTitleColor(.white),
                          .titleFont(.systemFont(ofSize: 14)),
                          .selectedTitleFont(.boldSystemFont(ofSize: 14)),
                          .cornerRadius(14)]
            )
```

In looking through the code, .titleColor and .titleFont seem to be missing now from the options in version 1.0.3.  

Please help. 

Thanks.

Jay

**Comment by gmarm** [comment]
Yes, indeed the API has been changed a bit to support custom segments. 

You can of course still customize your segments as you wish. Have a look at the [README](https://github.com/gmarm/BetterSegmentedControl#usage) and the example project, it's quite straightforward.

**Comment by jungalwala** [comment]
Thank you for the information and quick response.

In trying to use the new syntax, it looks like “titleColor” is no longer an identifier, is “titleColor” now “normalTextColor” and “titleFont” is now “normalFont”?

Jay

**Comment by jungalwala** [comment]
In case any cares, here is the converted syntax:

```
            let control = BetterSegmentedControl(
                frame: CGRect(x: 80, y: 0, width: 600, height: 28),
                segments: LabelSegment.segments(withTitles: ["All Tasks".localiz(), "All Tasks".localiz(), "All Tasks".localiz()],
                                                normalFont: UIFont.systemFont(ofSize: 14),
                                                normalTextColor: .black,
                                                selectedFont: UIFont.boldSystemFont(ofSize: 14),
                                                selectedTextColor: .white),
                index: 0,
                options: [.backgroundColor(UIColorFromRGB(0x8CA1B8)),
                          .indicatorViewBackgroundColor(UIColorFromRGB(0x0077ff)),
                          .cornerRadius(14)])
```

** Note, the order of the normalFont, normalTextColor, selectedFont, selectedTextColor matter.  When I had them in a different order the compiler could not recognize some of the attributes. **
