### ISSUE TITLE
Accessing to indicatorView position

### ISSUE THREAD

**Issue by artemKolyadin** [gmarm/BetterSegmentedControl#98]
Dear friend, thank you very much for great and useful control! 
I am configured two screens in one collectionView under BetterSegmentedControl() and need to update indicatorView.x position while user scrolling collectionView (between two cell). 
Please, can you say me how can i do it with this control? 

I need something like this: 

func scrollViewDidScroll(_ scrollView: UIScrollView) {
    let newX = scrollView.contentOffset.x / 2
    segmentedControl.indicatorView.frame.x = newX
  }

**Comment by gmarm** [comment]
Hmm this is not possible at the moment.

You can, however, when you move from cell to cell as you scroll call the `setIndex` method.
