### ISSUE TITLE
i have issue with alignment specialty in arabic RTL

### ISSUE THREAD

**Issue by aboud-masoud** [gmarm/BetterSegmentedControl#99]

**Comment by aboud-masoud** [comment]
Dear friend, thank you very much for great and useful control!
I am configured slider to my project and it's working good but the application have malti language (localization) and specially when i move to RTL the indicator not working

**Comment by aboud-masoud** [comment]
i solve it inside handlePanGesture()


  var translatedPoint = sender.translation(in: view).x
        if SharedReference.sharedInstance.isArabicLang {
            translatedPoint = -(sender.translation(in: view).x)
        }

**Comment by gmarm** [comment]
RTL support has been added as part of https://github.com/gmarm/BetterSegmentedControl/pull/112.
